# -*- coding: utf-8 -*-
"""datascience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rt-iEo6c7nU4ZY9lch6Eg_IE9UzCBC83
"""

import pandas as pd
notas = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/ml-latest-small/ratings.csv")
print(notas)

notas.columns = ["UsuarioID", "FilmeID", "notaID", "Momento"] #troquei o nome das colunas para facilitar a leitura em LISTA/ARRAY
so_notas = notas["notaID"]
print(so_notas.values)

tabelas = notas['notaID'].value_counts()
print(tabelas)
media = notas['notaID'].mean() #media

print(f"Minha média é: {media}")

import seaborn as sns
splot = sns.boxplot(notas['notaID'])
print(splot)

graficos = notas['notaID'].plot(kind="hist", bins=5, title="Distribuição das Notas") #kind="hist" → faz um histograma (mostra a distribuição das notas).
print(graficos)

